# for substitution expressions see:
# https://github.com/drone/envsubst?tab=readme-ov-file

server:
  host: ${NOTIFICATIONS_SERVER_HOST:-0.0.0.0}
  port: ${NOTIFICATIONS_SERVER_PORT:-8000}

pushClient:
  VapidPublicKey: ${VAPID_PUBLIC_KEY}
  VapidPrivateKey: ${VAPID_PRIVATE_KEY}
  timeout: ${NOTIFICATIONS_TIMEOUT:-30s}
