# for substitution expressions see:
# https://github.com/drone/envsubst?tab=readme-ov-file

server:
  host: ${NOTIFICATIONS_SERVER_HOST:-0.0.0.0}
  port: ${NOTIFICATIONS_SERVER_PORT:-8000}

auth:
  baseUrl: ${BASE_URL:-http://0.0.0.0:8000}
  path: ${PATH:-/session}
  timeout: ${AUTH_TIMEOUT:-30s}
  cookieName: ${COOKIE_NAME:-session_id}
  cookieDomain: ${COOKIE_DOMAIN:-/}

generateRecord:
  creation_shift: ${CREATION_SHIFT:-24h}
  batch_size: ${BATCH_SIZE:-1000}

generateDaemon:
  creation_shift: ${CREATION_SHIFT:-24h}
  ticker_interval: ${TICKER_INTERVAL:-24s}