# for substitution expressions see:
# https://github.com/drone/envsubst?tab=readme-ov-file

server:
  host: ${PLANNING_SERVER_HOST:-0.0.0.0}
  port: ${PLANNING_SERVER_PORT:-8000}

auth:
  authBaseUrl: ${AUTH_BASE_URL:-http://0.0.0.0:8000}
  path: ${PATH:-/session}
  timeout: ${AUTH_TIMEOUT:-30s}
  cookieName: ${COOKIE_NAME:-session_id}
  cookieDomain: ${COOKIE_DOMAIN:-/}

medication:
  endpoint: ${MEDICATION_SERVER_ENDPOINT:-http://medication:8000/internal/medication/}
  method: ${MEDICATION_METHOD:-GET}
  timeout: ${MEDICATION_TIMEOUT:-30s}

notification:
  endpoint: ${NOTIFICATIONS_SERVER_ENDPOINT:-http://notifications/notification/send}
  method: ${NOTIFICATION_METHOD:-POST}
  timeout: ${NOTIFICATION_TIMEOUT:-30s}